version: '3.9'

services:

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: docker/development/Dockerfile
    ports:
      - '5173:5173'
    restart: always
    env_file: 
      - ./.env.development
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/package.json:/usr/src/app/package.json
    depends_on:
      - server
    networks:
      - queue-net

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: docker/development/Dockerfile
    ports:
      - '5000:5000'
    env_file: 
      - ./.env.development
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/package.json:/usr/src/app/package.json
      - ./server/nodemon.json:/usr/src/app/nodemon.json
      - ./server/public:/usr/src/app/public
      - ./uploads:/app/uploads
    networks:
      - queue-net


networks:
  queue-net:
    driver: bridge

